# -*- coding: utf-8 -*-
"""number guessing game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ek6dCcD8TIZjgLVO8MmJeHEarqFSmD_6
"""

import numpy as np


print("choose difficulty")
print("1. easy")
print("2. medium")
print("3. hard")

choice =int(input("choose your difficulty level 1/2/3"))
if choice == 1:
  max_number = 50
  attempts = 10

elif choice == 2:
  max_number = 100
  attempts = 7

elif choice == 3:
  max_number = 500
  attempts = 5

else:
  print("invalid")
  exit()

secret_number = np.random.randint(1, max_number+1)
print(f"Guess a number between 1 and {max_number}")
print(f"You have {attempts} attempts.")

while attempts >0:

  guess = int(input("guess a number"))
  if guess > secret_number:
    print("too high")
    attempts = attempts -1

  elif guess < secret_number:
    print("too low")
    attempts = attempts -1

  else:
    print("congratulation you find the correct number")
    break
  print("attempts left:",attempts)

if attempts == 0:
  print("game over")
  print("the secret number was:", secret_number)